package dsl

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/brick-org/brick/dsl/codegen"
	"github.com/brick-org/brick/dsl/schema"
)

// EmitGo renders defs as a Go source file that defines them via the typed
// DSL (schema.Define + options).
//
// PK/parent columns are omitted from the Fields map — WithPK/WithParent
// re-inject them — so the output reads like hand-written DSL, not a dump.
// Field chains reuse codegen.FieldChainExpr, so emitted fields match
// generated SchemaFields byte-for-byte.
func EmitGo(pkg, funcName string, defs []schema.ResourceDef) (string, error) {
	if pkg == "" {
		return "", fmt.Errorf("dsl: emit: package name is required")
	}
	if funcName == "" {
		return "", fmt.Errorf("dsl: emit: function name is required")
	}
	sorted := make([]schema.ResourceDef, len(defs))
	copy(sorted, defs)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("// Code generated by brick dsl convert; DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	b.WriteString("import \"github.com/brick-org/brick/dsl/schema\"\n\n")
	b.WriteString(fmt.Sprintf("// %s returns all resource definitions.\n", funcName))
	b.WriteString(fmt.Sprintf("func %s() []schema.ResourceDef {\n", funcName))
	b.WriteString("\treturn []schema.ResourceDef{\n")
	for _, d := range sorted {
		expr, err := defineExpr(d)
		if err != nil {
			return "", err
		}
		b.WriteString("\t\t" + expr + ",\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("dsl: emit: format: %w", err)
	}
	return string(out), nil
}

func defineExpr(d schema.ResourceDef) (string, error) {
	if d.Schema == nil {
		return "", fmt.Errorf("dsl: emit: %s: nil schema", d.Name)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "schema.Define(%q, %q, schema.Fields{\n", d.Name, d.Table)

	pkCol := ""
	if pk := d.Schema.PK; pk != nil {
		pkCol = pk.Column
	}
	parentCol := ""
	if p := d.Schema.Parent; p != nil {
		parentCol = schema.ChildParentColumn(p.Resource)
	}
	for _, field := range schema.SortedFields(d.Schema.Fields, pkCol) {
		if field == pkCol || field == parentCol {
			continue // re-injected by WithPK / WithParent
		}
		fmt.Fprintf(&b, "\t\t\t%q: %s,\n", field, codegen.FieldChainExpr(d.Schema.Fields[field]))
	}
	b.WriteString("\t\t}")

	for _, opt := range resourceOptions(d) {
		b.WriteString(",\n\t\t" + opt)
	}
	b.WriteString(")")

	// defineExpr runs before gofmt, so validate the option exprs here.
	if _, err := pkExpr(d); err != nil {
		return "", err
	}
	return b.String(), nil
}

// resourceOptions renders the With* options in a fixed order so output is
// deterministic. Empty slots are omitted.
func resourceOptions(d schema.ResourceDef) []string {
	s := d.Schema
	var opts []string

	if disabled := disabledOps(d.Operations); len(disabled) > 0 {
		opts = append(opts, fmt.Sprintf("schema.WithOperations(schema.DisableOps(%s))", quoteList(disabled)))
	}
	if d.LookupField != "" {
		opts = append(opts, fmt.Sprintf("schema.WithLookup(%q)", d.LookupField))
	}
	if d.AutoCreate {
		opts = append(opts, "schema.WithAutoCreate()")
	}
	if pk, _ := pkExpr(d); pk != "" {
		opts = append(opts, "schema.WithPK("+pk+")")
	}
	if p := s.Parent; p != nil {
		if p.OnDelete != "" {
			opts = append(opts, fmt.Sprintf("schema.WithParent(schema.NewParent(%q, schema.%s))", p.Resource, onDeleteConst(p.OnDelete)))
		} else {
			opts = append(opts, fmt.Sprintf("schema.WithParent(schema.NewParent(%q))", p.Resource))
		}
	}
	if sg := s.Singleton; sg != nil {
		if sg.Scope != nil {
			opts = append(opts, fmt.Sprintf("schema.WithSingleton(schema.ScopedSingleton(%q, %q))", sg.Scope.Column, sg.Scope.Model))
		} else {
			opts = append(opts, "schema.WithSingleton(schema.Singleton())")
		}
	}
	for _, fk := range d.PolyFKs {
		if fk.OnDelete != "" {
			opts = append(opts, fmt.Sprintf("schema.WithPolyFKs(schema.NewPolyFK(%q, %q, %s, schema.%s))",
				fk.IDField, fk.TypeField, stringList(fk.AllowedTargets), onDeleteConst(fk.OnDelete)))
		} else {
			opts = append(opts, fmt.Sprintf("schema.WithPolyFKs(schema.NewPolyFK(%q, %q, %s))",
				fk.IDField, fk.TypeField, stringList(fk.AllowedTargets)))
		}
	}
	if s.TenantColumn != "" {
		opts = append(opts, fmt.Sprintf("schema.WithTenant(%q)", s.TenantColumn))
	}
	if s.TitleField != "" {
		opts = append(opts, fmt.Sprintf("schema.WithTitle(%q)", s.TitleField))
	}
	for _, group := range s.CompositeUniques {
		opts = append(opts, fmt.Sprintf("schema.WithUnique(%s)", quoteList(group)))
	}
	for _, group := range s.CompositeIndexes {
		opts = append(opts, fmt.Sprintf("schema.WithIndex(%s)", quoteList(group)))
	}
	if s.SoftDeleteColumn != "" {
		opts = append(opts, fmt.Sprintf("schema.WithSoftDelete(%q)", s.SoftDeleteColumn))
	}
	if s.Audited {
		opts = append(opts, "schema.WithAudit()")
	}
	if s.Versioned {
		opts = append(opts, "schema.WithVersioned()")
	}
	if len(s.UpdateWritable) > 0 {
		opts = append(opts, fmt.Sprintf("schema.WithWritableOnUpdate(%s)", quoteList(s.UpdateWritable)))
	}
	return opts
}

// disabledOps lists disabled operations in canonical order.
func disabledOps(ops schema.Operations) []string {
	var out []string
	if !ops.Enabled("get") {
		out = append(out, "get")
	}
	if !ops.Enabled("list") {
		out = append(out, "list")
	}
	if !ops.Enabled("create") {
		out = append(out, "create")
	}
	if !ops.Enabled("update") {
		out = append(out, "update")
	}
	if !ops.Enabled("delete") {
		out = append(out, "delete")
	}
	return out
}

func pkExpr(d schema.ResourceDef) (string, error) {
	pk := d.Schema.PK
	if pk == nil {
		return "", nil
	}
	col := fmt.Sprintf("%q", pk.Column)
	switch pk.Autoname.Strategy {
	case schema.AutonameUUID:
		return fmt.Sprintf("schema.UUIDPK(%s)", col), nil
	case schema.AutonameSeries:
		return fmt.Sprintf("schema.SeriesPK(%s, %q)", col, pk.Autoname.Template), nil
	case schema.AutonameFromField:
		return fmt.Sprintf("schema.FieldPK(%s, %q)", col, pk.Autoname.Source), nil
	case schema.AutonameFormat:
		return fmt.Sprintf("schema.FormatPK(%s, %q)", col, pk.Autoname.Template), nil
	case schema.AutonameHash:
		return fmt.Sprintf("schema.HashPK(%s, %d)", col, pk.Autoname.HashLen), nil
	case schema.AutonamePrompt:
		return fmt.Sprintf("schema.PromptPK(%s)", col), nil
	case schema.AutonameAutoinc:
		return fmt.Sprintf("schema.AutoincPK(%s)", col), nil
	}
	return "", fmt.Errorf("dsl: emit: %s: unknown pk strategy %q", d.Name, pk.Autoname.Strategy)
}

func onDeleteConst(a schema.OnDeleteAction) string {
	switch a {
	case schema.Cascade:
		return "Cascade"
	case schema.SetNull:
		return "SetNull"
	case schema.SetDefault:
		return "SetDefault"
	case schema.Restrict:
		return "Restrict"
	case schema.NoAction:
		return "NoAction"
	}
	return ""
}

func quoteList(vals []string) string {
	quoted := make([]string, len(vals))
	for i, v := range vals {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}

func stringList(vals []string) string {
	if vals == nil {
		return "nil"
	}
	return "[]string{" + quoteList(vals) + "}"
}
