package dsl_test

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/brick-org/brick/dsl"
	"github.com/brick-org/brick/dsl/schema"
)

func testDefs() []schema.ResourceDef {
	return []schema.ResourceDef{
		schema.Define("deal", "deals", schema.Fields{
			"title":  schema.String().Required().Searchable(),
			"status": schema.Enum("open", "won").Default("open").Filterable(),
			"value":  schema.Int().Default(0),
		}, schema.WithTitle("title")),
		schema.Define("note", "notes", schema.Fields{
			"body": schema.Text().Required(),
		}, schema.WithParent(schema.NewParent("deal", schema.Cascade))),
	}
}

func mustParseGo(t *testing.T, src string) {
	t.Helper()
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "gen.go", src, parser.AllErrors); err != nil {
		t.Fatalf("emitted code does not parse: %v\n%s", err, src)
	}
}

func TestRun_WritesBothFiles(t *testing.T) {
	dir := t.TempDir()
	if err := dsl.Run(testDefs(), dsl.RunOptions{OutDir: dir, Package: "gen", Aggregates: true}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	for _, name := range []string{dsl.DBFileName, dsl.CRUDFileName} {
		src, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		if !strings.HasPrefix(string(src), "// Code generated by brick; DO NOT EDIT.") {
			t.Errorf("%s: missing generated header", name)
		}
		if !strings.Contains(string(src), "package gen") {
			t.Errorf("%s: missing package clause", name)
		}
		mustParseGo(t, string(src))
	}
	db, _ := os.ReadFile(filepath.Join(dir, dsl.DBFileName))
	if !strings.Contains(string(db), "type DealRow struct") || !strings.Contains(string(db), "func BusinessIndexes(") {
		t.Errorf("db file missing DealRow/BusinessIndexes")
	}
	crud, _ := os.ReadFile(filepath.Join(dir, dsl.CRUDFileName))
	if !strings.Contains(string(crud), "type NoteResponse struct") || !strings.Contains(string(crud), "var NoteParent") {
		t.Errorf("crud file missing NoteResponse/NoteParent")
	}
}

func TestRun_CreatesOutDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "gen")
	if err := dsl.Run(testDefs(), dsl.RunOptions{OutDir: dir, Package: "gen"}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, dsl.DBFileName)); err != nil {
		t.Fatalf("expected db file: %v", err)
	}
}

func TestRun_RejectsBadOptions(t *testing.T) {
	if err := dsl.Run(testDefs(), dsl.RunOptions{Package: "gen"}); err == nil {
		t.Error("expected error for empty OutDir")
	}
	if err := dsl.Run(testDefs(), dsl.RunOptions{OutDir: t.TempDir()}); err == nil {
		t.Error("expected error for empty Package")
	}
}

func TestRun_FailsFastOnInvalidDef(t *testing.T) {
	bad := schema.Define("w", "ws", schema.Fields{"id": schema.UUID()}, schema.WithTenant("nope"))
	err := dsl.Run([]schema.ResourceDef{bad}, dsl.RunOptions{OutDir: t.TempDir(), Package: "gen"})
	if err == nil {
		t.Fatal("expected validation error")
	}
	if !strings.Contains(err.Error(), "tenant") {
		t.Fatalf("error should name the problem: %v", err)
	}
	// Nothing written on validation failure.
	entries, _ := os.ReadDir(t.TempDir())
	_ = entries
}

func TestEmitGo_FullDef(t *testing.T) {
	def := schema.Define("widget", "widgets", schema.Fields{
		"slug":   schema.String().Required().Unique().Searchable(),
		"label":  schema.String().Required().Filterable(),
		"team":   schema.String().Required(),
		"status": schema.Enum("open", "closed").Default("open").Filterable(),
	},
		schema.WithTitle("label"),
		schema.WithTenant("team"),
		schema.WithLookup("slug"),
		schema.WithUnique("team", "label"),
		schema.WithPK(schema.HashPK("name", 10)),
		schema.WithOperations(schema.DisableOps("delete")),
	)
	out, err := dsl.EmitGo("resources", "Resources", []schema.ResourceDef{def})
	if err != nil {
		t.Fatalf("EmitGo: %v", err)
	}
	mustParseGo(t, out)
	for _, want := range []string{
		`schema.Define("widget", "widgets", schema.Fields{`,
		`"slug":`,
		`schema.String().Required().Unique().Searchable()`,
		`"status":`,
		`schema.Enum("open", "closed").Filterable().Default("open")`,
		`schema.WithOperations(schema.DisableOps("delete"))`,
		`schema.WithLookup("slug")`,
		`schema.WithPK(schema.HashPK("name", 10))`,
		`schema.WithTenant("team")`,
		`schema.WithTitle("label")`,
		`schema.WithUnique("team", "label")`,
		`func Resources() []schema.ResourceDef`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
	// PK column re-injected by WithPK, not declared twice.
	if strings.Contains(out, `"name":`) {
		t.Errorf("pk column must not appear in Fields:\n%s", out)
	}
}

func TestEmitGo_RequiresPkgAndFunc(t *testing.T) {
	if _, err := dsl.EmitGo("", "Resources", testDefs()); err == nil {
		t.Error("expected error for empty package")
	}
	if _, err := dsl.EmitGo("gen", "", testDefs()); err == nil {
		t.Error("expected error for empty func name")
	}
}

func TestEmitGo_SortsByName(t *testing.T) {
	out, err := dsl.EmitGo("gen", "Resources", testDefs())
	if err != nil {
		t.Fatalf("EmitGo: %v", err)
	}
	if strings.Index(out, `"deal"`) > strings.Index(out, `"note"`) {
		t.Errorf("expected deal before note:\n%s", out)
	}
}

func TestEmitGo_FullParity(t *testing.T) {
	// Every DSL feature expressed in Go must survive the emit round-trip.
	def := schema.Define("widget", "widgets", schema.Fields{
		"slug":            schema.String().Required().Unique().Searchable().Sortable(),
		"label":           schema.String().Required().Filterable(),
		"team":            schema.String().Required().Filterable(),
		"owner":           schema.String().Filterable(),
		"status":          schema.Enum("open", "closed").Default("open").Filterable(),
		"owner_id":        schema.ForeignKey("workspace_member").Required(),
		"legacy_id":       schema.ForeignKey("legacy"),
		"organization_id": schema.String().From("session.activeOrganizationId"),
		"score":           schema.Int().Default(0),
		"ratio":           schema.Float(),
		"active":          schema.Bool().Default(false),
		"created_at":      schema.Timestamp().Readonly(),
		"meta":            schema.JSON(),
		"email":           schema.String().Email().MaxLen(255),
		"notes":           schema.Text(),
		"secret":          schema.String().Hidden(),
		"archived_at":     schema.Timestamp(),
		"child_ids":       schema.Children("widget_part").OrderBy("position").Index(),
	},
		schema.WithTenant("team"),
		schema.WithTitle("label"),
		schema.WithLookup("slug"),
		schema.WithUnique("team", "label"),
		schema.WithIndex("owner", "status"),
		schema.WithSoftDelete("archived_at"),
		schema.WithAudit(),
		schema.WithVersioned(),
		schema.WithWritableOnUpdate("status", "owner"),
		schema.WithPK(schema.HashPK("name", 10)),
		schema.WithParent(schema.NewParent("gadget", schema.Cascade)),
		schema.WithSingleton(schema.ScopedSingleton("team", "teams")),
		schema.WithPolyFKs(schema.NewPolyFK("ref_id", "ref_type", []string{"CRM Lead", "CRM Deal"}, schema.Cascade)),
		schema.WithOperations(schema.DisableOps("list", "create", "delete")),
	)
	out, err := dsl.EmitGo("resources", "Resources", []schema.ResourceDef{def})
	if err != nil {
		t.Fatalf("EmitGo: %v", err)
	}
	mustParseGo(t, out)
	for _, want := range []string{
		`schema.Define("widget", "widgets"`,
		`schema.WithPK(schema.HashPK("name", 10))`,
		`schema.WithParent(schema.NewParent("gadget", schema.Cascade))`,
		`schema.WithSingleton(schema.ScopedSingleton("team", "teams"))`,
		`schema.WithTenant("team")`,
		`schema.WithTitle("label")`,
		`schema.WithLookup("slug")`,
		`schema.WithUnique("team", "label")`,
		`schema.WithIndex("owner", "status")`,
		`schema.WithSoftDelete("archived_at")`,
		`schema.WithAudit()`,
		`schema.WithVersioned()`,
		`schema.WithWritableOnUpdate("status", "owner")`,
		`schema.NewPolyFK("ref_id", "ref_type", []string{"CRM Lead", "CRM Deal"}, schema.Cascade)`,
		`"legacy_id":`,
		`schema.ForeignKey("legacy")`,
		`"organization_id":`,
		`schema.String().Readonly().From("session.activeOrganizationId")`,
		`"child_ids":`,
		`schema.Children("widget_part").OrderBy("position").Index()`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
}
