// Code generated by auth/transpiler; DO NOT EDIT.
// Source: vendor/better-auth/packages/better-auth/src/utils/boolean.ts
// Source SHA-256: ab05c35e80ed4268d6050d1c9edd6d7b3db338f6b11f1de0c31e06d612438a37
// IR version: 3
package utils

// ToBoolean transpiled from vendor/better-auth/packages/better-auth/src/utils/boolean.ts:1:1.
func ToBoolean(value any) bool {
	return ((func() bool { v, ok := value.(string); return ok && v == "true" }()) || (func() bool { v, ok := value.(bool); return ok && v == true }()))
}
