// Code generated by auth/transpiler; DO NOT EDIT.
// Source: vendor/better-auth/packages/better-auth/src/utils/constants.ts
// Source SHA-256: 6ff6aa9b20bd5bbc7b769979b42a843caeb1e0c7a4c9302ed480faa594e83edf
// IR version: 3
package utils

// DefaultSecret transpiled from vendor/better-auth/packages/better-auth/src/utils/constants.ts:1:1.
const DefaultSecret = "better-auth-secret-12345678901234567890"
