// Code generated by auth/transpiler; DO NOT EDIT.
// Source: vendor/better-auth/packages/better-auth/src/utils/hide-metadata.ts
// Source SHA-256: 98fb565c5cb6b32cad91654c3c31ee0cfc5431fa736c86883011e0f570eac9be
// IR version: 3
package utils

// HideMetadata transpiled from vendor/better-auth/packages/better-auth/src/utils/hide-metadata.ts:1:1.
var HideMetadata = map[string]string{
	"scope": "server",
}
