// Package codegen emits Go source from ResourceDefs: bun row models
// (GenerateDB) and CRUD input/output types plus schema vars
// (GenerateCRUD). Output is gofmt-clean and deterministic; golden files
// in testdata/ pin it. There are exactly two entry points — no
// GenerateAll.
package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/brick-org/brick/dsl/schema"
)

// ResourceDef is the codegen input. It aliases schema.ResourceDef so the
// DSL output feeds the emitters with no mapping layer.
type ResourceDef = schema.ResourceDef

// Options controls generation behaviour.
type Options struct {
	Aggregates bool
}

// GenerateDB produces models_db content: Row structs, BusinessModels,
// BusinessIndexes.
func GenerateDB(pkg string, resources []ResourceDef, opts Options) (string, error) {
	resources = sortedByName(resources)
	var b strings.Builder

	hasTime, hasJSON := scanFieldTypes(resources)

	b.WriteString("// Code generated by brick; DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	b.WriteString("import (\n")
	if opts.Aggregates {
		b.WriteString("\t\"context\"\n")
	}
	if hasJSON {
		b.WriteString("\t\"encoding/json\"\n")
	}
	if hasTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\t\"github.com/uptrace/bun\"\n")
	b.WriteString(")\n\n")

	if opts.Aggregates {
		b.WriteString("// BusinessModels returns all business table models for migration.\n")
		b.WriteString("func BusinessModels() []any {\n")
		b.WriteString("\treturn []any{\n")
		for _, r := range resources {
			b.WriteString(fmt.Sprintf("\t\t(*%sRow)(nil),\n", schema.Title(r.Name)))
		}
		if needsNamingCounter(resources) {
			b.WriteString("\t\t(*NamingSeriesCounterRow)(nil),\n")
		}
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	for _, r := range resources {
		emitRow(&b, r)
	}

	if needsNamingCounter(resources) {
		emitNamingCounterRow(&b)
	}

	if opts.Aggregates {
		writeBusinessIndexes(&b, resources)
	}

	return formatOutput(b.String())
}

// GenerateCRUD produces models_crud content: Response, CreateBody,
// UpdateBody, ListInput, ToListOptions, Schema/Access/Hooks aliases,
// and SchemaFields/PK/Parent/Singleton vars.
func GenerateCRUD(pkg string, resources []ResourceDef) (string, error) {
	resources = sortedByName(resources)
	hasTime, hasJSON := scanFieldTypes(resources)

	byName := make(map[string]ResourceDef, len(resources))
	for _, r := range resources {
		byName[r.Name] = r
	}

	var b strings.Builder

	b.WriteString("// Code generated by brick; DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	b.WriteString("import (\n")
	if hasJSON {
		b.WriteString("\t\"encoding/json\"\n")
	}
	if hasTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\t\"github.com/brick-org/brick/brick\"\n")
	b.WriteString("\t\"github.com/brick-org/brick/brick/db\"\n")
	b.WriteString("\t\"github.com/brick-org/brick/dsl/schema\"\n")
	b.WriteString(")\n\n")

	for _, r := range resources {
		emitCRUD(&b, r, byName)
	}

	return formatOutput(b.String())
}

// sortedByName orders defs by Name so output is deterministic regardless
// of LoadDir or caller order.
func sortedByName(resources []ResourceDef) []ResourceDef {
	out := make([]ResourceDef, len(resources))
	copy(out, resources)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func scanFieldTypes(resources []ResourceDef) (hasTime, hasJSON bool) {
	for _, r := range resources {
		for _, def := range r.Schema.Fields {
			if def.Type == schema.FieldTimestamp {
				hasTime = true
			}
			if def.Type == schema.FieldJSON {
				hasJSON = true
			}
		}
	}
	return
}

// childTypeRef resolves a children field to the child resource's generated
// type name, falling back to an untyped map when the child isn't generated
// in the same package.
func childTypeRef(def *schema.FieldDef, byName map[string]ResourceDef, suffix string) string {
	if _, ok := byName[def.ChildrenOf]; ok {
		return schema.Title(def.ChildrenOf) + suffix
	}
	return "map[string]any"
}
